In [1]:
import numpy as np

In [2]:
L = 5
a = np.array([range(0,L*L)]).reshape(L,L)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [10]:
def neighbor(L, x):
    total_cells = L * L  # 총 셀 수

    right_neighbor = (x + 1) if (x + 1) % L != 0 else x + 1 - L
    left_neighbor = (x - 1) if x % L != 0 else x - 1 + L
    up_neighbor = (x - L) if x - L >= 0 else x - L + total_cells
    down_neighbor = (x + L) if x + L < total_cells else x + L - total_cells

    return np.array([left_neighbor, right_neighbor, up_neighbor, down_neighbor])

In [11]:
neighbor(L,5)

array([ 9,  6,  0, 10])

In [12]:
L = 5

random_arr = np.random.randn(L*L) # 평균이 0이고 분산이 1인 표준 정규 분포에서 무작위 값을 가지는 길이 25의 배열을 생성

S = random_arr/abs(random_arr) # random_arr의 각 요소를 그 절댓값으로 나눠 S 배열을 생성

print(S)
print(len(S))

[-1.  1.  1. -1.  1. -1. -1.  1.  1. -1. -1.  1.  1.  1.  1. -1. -1. -1.
  1. -1. -1.  1.  1. -1. -1.]
25


In [13]:
def neighbor_E(arr, L, x):
  return -np.sum(arr[neighbor(L,x)])*arr[x]

In [14]:
E = 0

for x in range(len(S)):# 모든 "연결"에 관하여 계산한다
    E += (neighbor_E(S, L, x))

print('E =', E/2) # a에서 b의 계산은 b에서 a의 계산과 같으므로 2로 나눈다.

E = -2.0
