# 너비 우선 탐색

In [1]:
import numpy as np
import queue

In [8]:
# 인접 리스트

N, Kmax = 8, 4
K = np.array([1,2,4,1,1,3,1,1]) # 이웃의 수
nn = np.empty([N,Kmax], int) # 이웃들
nn[0] = np.array([2,-1,-1,-1])
nn[1] = np.array([2,5,-1,-1])
nn[2] = np.array([0,1,3,4])
nn[3] = np.array([2,-1,-1,-1])
nn[4] = np.array([2,-1,-1,-1])
nn[5] = np.array([1,6,7,-1])
nn[6] = np.array([5,-1,-1,-1])
nn[7] = np.array([5,-1,-1,-1])

[[ 2 -1 -1 -1]
 [ 2  5 -1 -1]
 [ 0  1  3  4]
 [ 2 -1 -1 -1]
 [ 2 -1 -1 -1]
 [ 1  6  7 -1]
 [ 5 -1 -1 -1]
 [ 5 -1 -1 -1]]


In [ ]:
discovered = np.array([-1] * N)

def bfs(K, nn, start, discovered):
    q = queue.Queue()
    q.put(start)
    discovered[start] = 0 # 출발점을 0으로 부터 시작
    while q.qsize() > 0: # q에 원소가 남아있는 한 계속 실행
        element = q.get() # 큐에서 한 점을 뽑음
        for i in range(K[element]):
            neighbor = nn[element][i]
            if neighbor != -1 and discovered[neighbor] == -1:
                q.put(neighbor)
                discovered[neighbor] = discovered[element] + 1
    return discovered

In [ ]:
print(bfs(K, nn, 0, discovered))

[0 2 1 2 2 3 4 4]


# 깊이 우선 탐색

In [ ]:
def dfs(K, nn, start, discovered):